development:
  adapter: postgresql
  encoding: unicode
  database: gradr_development
  pool: 5
  username: Sean
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: gradr_test
  pool: 5
  username: Sean
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: gradr_production
  pool: 5
  username: Sean
  password:
